cloudflare:
  r2:
    access-key: admin
    secret-key: password
    endpoint: http://localhost:9000
    bucket: casse-bucket

spring:
  data:
    redis:
      url: redis://localhost:6666
  datasource:
    url: jdbc:postgresql://localhost:1414/casse_db
    jpa:
      hibernate:
        ddl-auto: create