cloudflare:
  r2:
    access-key: admin
    secret-key: password
    endpoint: http://minio:9000
    bucket: casse-bucket

spring:
  data:
    redis:
      url: redis://redis:6666
  datasource:
    url: jdbc:postgresql://postgres:1414/casse_db
    jpa:
      hibernate:
        ddl-auto: create